version: "3.9"

services:
  wpdb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
      MYSQL_DATABASE: wpdb

  wpadminer:
    image: adminer
    restart: always
    ports:
      - "8881:8080"